enhancement:
  - head-branch: ["^feature/"]

bug:
  - any:
      - head-branch: ["^bugfix/", "^hotfix/"]

cleanup:
  - head-branch: ["^chore/"]

client:
  - changed-files:
      - AnyGlobToAnyFile: ["client/**/*"]

client-components:
  - changed-files:
      - AnyGlobToAnyFile: ["client/components/**/*"]

client-hooks:
  - changed-files:
      - AnyGlobToAnyFile: ["client/hooks/**/*"]

client-config:
  - changed-files:
      - AnyGlobToAnyFile: ["client/*.config.js", "client/*.config.ts"]

client-pages:
  - changed-files:
      - AnyGlobToAnyFile: ["client/app/**/*"]

client-constants:
  - changed-files:
      - AnyGlobToAnyFile: ["client/constants/**/*"]

client-context:
  - changed-files:
      - AnyGlobToAnyFile: ["client/context/**/*"]

client-interfaces:
  - changed-files:
      - AnyGlobToAnyFile: ["client/interfaces/**/*"]

client-public:
  - changed-files:
      - AnyGlobToAnyFile: ["client/public/**/*"]

server:
  - changed-files:
      - AnyGlobToAnyFile: ["server/**/*"]

server-controllers:
  - changed-files:
      - AnyGlobToAnyFile: ["server/src/controllers/**/*"]

server-routes:
  - changed-files:
      - AnyGlobToAnyFile: ["server/src/routes/**/*"]

server-middleware:
  - changed-files:
      - AnyGlobToAnyFile: ["server/src/middleware/**/*"]

docker:
  - changed-files:
      - AnyGlobToAnyFile: ["server/*.dockerignore", "server/docker-*.sh", "server/Dockerfile*", "server/docker-compose*.yml"]

github:
  - changed-files:
      - AnyGlobToAnyFile: [".github/**/*"]

root:
  - changed-files:
      - AnyGlobToAnyFile: ["/*.*", "/.gitignore"]

config-utilities:
  - changed-files:
      - AnyGlobToAnyFile: ["client/lib/**/*", "server/src/utils/**/*"]

database:
  - changed-files:
      - AnyGlobToAnyFile: ["server/prisma/**/*"]
