enhancement:
  - head-branch: ["^feature/"]

bug:
  - head-branch: ["^bugfix/", "^hotfix/"]

cleanup:
  - head-branch: ["^chore/"]

client:
  - changed-files:
      - AnyGlobToAnyFile: ["client/**/*"]

server:
  - changed-files:
      - AnyGlobToAnyFile: ["server/**/*"]

docker:
  - changed-files:
      - AnyGlobToAnyFile:
          ["server/*.dockerignore", "server/docker-*.sh", "server/Dockerfile*", "server/docker-compose*.yml"]

github:
  - changed-files:
      - AnyGlobToAnyFile: [".github/**/*"]

root:
  - changed-files:
      - AnyGlobToAnyFile: ["/*.*", "/.gitignore"]

config-utilities:
  - changed-files:
      - AnyGlobToAnyFile: ["**/*.config.js", "**/*.config.ts", "client/lib/**/*", "server/src/utils/**/*"]

database:
  - changed-files:
      - AnyGlobToAnyFile: ["server/prisma/**/*"]
