export const categories = [
  "Anything",
  "Home Decor",
  "Fashion",
  "Garden Projects",
  "Kids Crafts",
  "Jewelry Making",
  "Woodworking",
  "Paper Crafts",
  "Pottery & Clay Projects",
  "Textile & Sewing",
  "Upcycling",
  "Holiday Crafts",
  "Tech DIYs",
  "Beauty & Personal Care",
  "Outdoor Projects",
  "Kitchen Crafts",
  "Pet Crafts",
  "Furniture Makeovers",
  "Art Projects",
  "Photography DIYs",
  "Musical Instruments",
  "Car & Mechanical Crafts",
  "Eco-friendly Crafts",
  "Baking & Food Crafts",
  "Travel & Adventure DIYs",
];
