FROM node:16-slim

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y openssl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

COPY package*.json ./

RUN npm install

COPY . ./

EXPOSE 3000
EXPOSE $PORT

COPY docker-dev.sh /usr/src/app/docker-dev.sh

RUN chmod +x /usr/src/app/docker-dev.sh

CMD ["/usr/src/app/docker-dev.sh"]