"use client";

import { useEffect, useState } from "react";
import { CommunityIdeaData } from "@/interfaces";

import { getCommunityGeneratedIdea } from "@/lib/index";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/components/ui/use-toast";
import ProjectCard from "@/components/community/diy-card";

export default function CommunityGeneratedIdeaList() {
  const [communityData, setCommunityData] = useState<CommunityIdeaData[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  useEffect(() => {
    const fetchCommunityGeneratedIdeas = async () => {
      try {
        const fetchedCommunityGeneratedIdea = await getCommunityGeneratedIdea();
        setCommunityData(fetchedCommunityGeneratedIdea.data);
      } catch (error) {
        console.error(error);
        toast({
          title: "Oops!",
          description: "Failed to fetch community generated ideas. Please try again later.",
        });
      } finally {
        setLoading(false);
      }
    };

    fetchCommunityGeneratedIdeas();
  }, [toast]);

  return (
    <div className="container mx-auto px-5 py-12 sm:px-10">
      <div className="mb-12 text-center">
        <h1 className="mb-3 text-3xl font-semibold lg:text-4xl">&ldquo;MakeMeDIYspire&rdquo; Community Generated Idea</h1>
        <Label className="sm:text-md mt-2 inline-block text-sm">
          Explore a myriad of innovative DIY ideas generated by our creative community members. Dive into the inspiration behind each project and kickstart your next DIY journey.
        </Label>
      </div>

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
        {loading
          ? [...Array(3)].map((_, i) => (
              <div key={i}>
                <Skeleton className="mb-5 h-10 w-full" />
                <div className="space-y-2">
                  <Skeleton className="h-4 w-full" />
                  <Skeleton className="h-4 w-full" />
                </div>
                <Skeleton className="mt-5 h-4 w-3/5" />
              </div>
            ))
          : communityData.map(({ id, title, description, tags, projectImage, createdAt }) => (
              <ProjectCard key={id} id={id} title={title} description={description} badges={tags} imgUrl={projectImage.urls.small} createdAt={createdAt} />
            ))}
      </div>
    </div>
  );
}
