"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useCommunityGeneratedIdea } from "@/api/queries";
import { AxiosError } from "axios";

import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Pagination, PaginationContent, PaginationEllipsis, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from "@/components/ui/pagination";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/components/ui/use-toast";
import ProjectCard from "@/components/community/diy-card";

export default function CommunityGeneratedIdeaList() {
  const [currentPage, setCurrentPage] = useState(1);
  const limitPerPage = 10;

  const { toast } = useToast();

  const { data: communityData, error, isLoading, isSuccess } = useCommunityGeneratedIdea({ page: currentPage, limit: limitPerPage, orderBy: "desc" });

  const totalPages = communityData?.data.totalCount ? Math.ceil(communityData?.data.totalCount / limitPerPage) : 0;

  useEffect(() => {
    if (error && error instanceof AxiosError) {
      const errorMessage = error.response?.data.error || "An error occurred while fetching data from the API.";

      toast({
        title: `API ERROR - ${error.code}`,
        description: errorMessage,
      });
    } else if (error) {
      toast({
        title: "Unexpected Error!",
        description: "An unexpected error occurred. Please try again later.",
      });
    }
  }, [error, toast]);

  const renderLoadingSkeleton = () => {
    return (
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
        <div>
          <Skeleton className="mb-5 h-10 w-full" />
          <div className="space-y-2">
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-full" />
          </div>
          <Skeleton className="mt-5 h-4 w-3/5" />
        </div>
      </div>
    );
  };

  const renderNoDataDisplay = () => (
    <div className="flex h-full flex-col items-center justify-center">
      <Label className=" text-md mt-2 inline-block">No community ideas found.</Label>
      <Link href="/">
        <Button className="mt-2" aria-label="Generate one">
          Generate one
        </Button>
      </Link>
    </div>
  );

  const renderProjectCards = () => {
    return (
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
        {communityData?.data.projects.map(({ id, slug, title, description, tags, projectImage, createdAt }) => (
          <ProjectCard key={id} id={id} slug={slug} title={title} description={description} badges={tags} imgUrl={projectImage.urls.small} createdAt={createdAt} />
        ))}
      </div>
    );
  };

  return (
    <div className="container mx-auto px-5 py-12 sm:px-10">
      <div className="mb-12 text-center">
        <h1 className="mb-3 text-3xl font-semibold lg:text-4xl">&ldquo;MakeMeDIYspire&rdquo; Community Generated Idea</h1>
        <Label className="sm:text-md mt-2 inline-block text-sm">
          Explore a myriad of innovative DIY ideas generated by our creative community members. Dive into the inspiration behind each project and kickstart your next DIY journey.
        </Label>
      </div>
      {isLoading ? renderLoadingSkeleton() : isSuccess && communityData.data.totalCount > 0 ? renderProjectCards() : renderNoDataDisplay()}
      {isSuccess && (
        <Pagination className="mt-8 flex items-center justify-center">
          <PaginationContent>
            <PaginationItem>
              <PaginationPrevious onClick={() => setCurrentPage((prev) => (prev > 1 ? prev - 1 : prev))} aria-disabled={currentPage === 1} />
            </PaginationItem>

            <PaginationItem>
              <PaginationLink isActive={currentPage === 1} onClick={() => setCurrentPage(1)}>
                1
              </PaginationLink>
            </PaginationItem>
            {currentPage > 3 && (
              <PaginationItem>
                <PaginationEllipsis />
              </PaginationItem>
            )}
            {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
              const page = currentPage - 2 + i;
              if (page > 1 && page < totalPages) {
                return (
                  <PaginationItem key={page}>
                    <PaginationLink isActive={currentPage === page} onClick={() => setCurrentPage(page)}>
                      {page}
                    </PaginationLink>
                  </PaginationItem>
                );
              }
              return null;
            }).filter(Boolean)}
            {currentPage < totalPages - 2 && (
              <PaginationItem>
                <PaginationEllipsis />
              </PaginationItem>
            )}
            {totalPages > 1 && (
              <PaginationItem>
                <PaginationLink isActive={currentPage === totalPages} onClick={() => setCurrentPage(totalPages)}>
                  {totalPages}
                </PaginationLink>
              </PaginationItem>
            )}
            <PaginationItem>
              <PaginationNext onClick={() => setCurrentPage((prevPage) => Math.min(prevPage + 1, totalPages))} aria-disabled={currentPage === totalPages} />
            </PaginationItem>
          </PaginationContent>
        </Pagination>
      )}
    </div>
  );
}
